import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";


const HomeContents = () => {
  const {data} = useSession();

  if(!data) {
    return <button onClick={() => signIn()}>Logga in</button>
  }
  
  return  (
    <>
    <div>Hej {data.user?.name}!</div>
    <button onClick={() => signOut()}>Logga ut</button>
    </>
  )

}

const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeContents />
    </>
  );
};

export default Home;
 